services:
    user1:
        command: "sleep infinity"
#        command: "chatapp"
#        depends_on:
        image: chatprj
#        networks:
#        ports:
        volumes:
            - type: bind
              source: /home/user/my/qt_projects/build-chatprj-Desktop-RelWithDebInfo
              target: /my/app
            - type: bind
              source: /home/user/sources/cmake/cmake-3.24.0-linux-x86_64
              target: /my/cmake



#volumes:
