services:
    user1:
#    command: "sleep infinity"
        command: "/my/app/chatapp"
        environment:
            XDG_SESSION_TYPE: wayland
            XDG_RUNTIME_DIR: /tmp
            WAYLAND_DISPLAY: $WAYLAND_DISPLAY
            QT_QPA_PLATFORM: wayland
#        command: "chatapp"
#        depends_on:
        image: chatprj
#        networks:
#        ports:
        volumes:
            - type: bind
              source: /home/user/my/qt_projects/build-chatprj-Desktop-RelWithDebInfo
              target: /my/app
            - type: bind
              source: /home/user/sources/cmake/cmake-3.24.0-linux-x86_64
              target: /my/cmake
            - type: bind
              source: $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY
              target: /tmp/$WAYLAND_DISPLAY

#volumes:
