services:

    client1:
    #    command: "sleep infinity"
#        command: ["/my/app/chatapp", "--app"]
        command: /my/app/chatapp --app
        environment:
            XDG_SESSION_TYPE: wayland
            XDG_RUNTIME_DIR: /tmp
            WAYLAND_DISPLAY: $WAYLAND_DISPLAY
            QT_QPA_PLATFORM: wayland
        image: chatprj
        networks:
            my-bridge-network:
                ipv4_address: 172.21.0.2
        expose:
            - "5002"
        volumes:
            - type: bind
              source: /home/user/my/qt_projects/build-chatprj-Desktop-RelWithDebInfo
              target: /my/app
            - type: bind
              source: /home/user/sources/cmake/cmake-3.24.0-linux-x86_64
              target: /my/cmake
            - type: bind
              source: $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY
              target: /tmp/$WAYLAND_DISPLAY

    client2:
    #    command: "sleep infinity"
#        command: ["/my/app/chatapp", "--app"]
        command: /my/app/chatapp --app
        environment:
            XDG_SESSION_TYPE: wayland
            XDG_RUNTIME_DIR: /tmp
            WAYLAND_DISPLAY: $WAYLAND_DISPLAY
            QT_QPA_PLATFORM: wayland
        image: chatprj
        networks:
            my-bridge-network:
                ipv4_address: 172.21.0.3
        expose:
            - "5002"
        volumes:
            - type: bind
              source: /home/user/my/qt_projects/build-chatprj-Desktop-RelWithDebInfo
              target: /my/app
            - type: bind
              source: /home/user/sources/cmake/cmake-3.24.0-linux-x86_64
              target: /my/cmake
            - type: bind
              source: $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY
              target: /tmp/$WAYLAND_DISPLAY

    client1_db:
        image: chatprj_db
        networks:
            my-bridge-network:
                ipv4_address: 172.21.0.4
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres123
        ports:
            - "5433:5432"
        volumes:
            - chatapp_volume1:/var/lib/postgresql/data
            - type: bind
              source: /home/user/my/qt_projects/build-chatprj-Desktop-RelWithDebInfo
              target: /my/app
              # db setting scripts, run only when no db exists, to run scripts recreate docker volumes
            - type: bind
              source: /home/user/my/qt_projects/build-chatprj-Desktop-RelWithDebInfo/sql_scripts/client1_db
              target: /docker-entrypoint-initdb.d

    client2_db:
        image: chatprj_db
        networks:
            my-bridge-network:
                ipv4_address: 172.21.0.5
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres123
        ports:
            - "5434:5432"
        volumes:
            - chatapp_volume2:/var/lib/postgresql/data
            - type: bind
              source: /home/user/my/qt_projects/build-chatprj-Desktop-RelWithDebInfo
              target: /my/app
              # db setting scripts, run only when no db exists, to run scripts recreate docker volumes
            - type: bind
              source: /home/user/my/qt_projects/build-chatprj-Desktop-RelWithDebInfo/sql_scripts/client2_db
              target: /docker-entrypoint-initdb.d

networks:
    my-bridge-network:
        external: true
        driver: bridge
        ipam:
            config:
                - subnet: 172.21.0.0/16

volumes:
    chatapp_volume1:
    chatapp_volume2:
